### ISSUE TITLE
[Bases de datos] Consultas SQL indicadas por el docente, 1ra. Versión.

### ISSUE THREAD

**Issue by Katherine-Damires** [Katherine-Damires/2021_Proyecto_Integrador_Equipo_4#41]
Mostrando datos de prueba, que
permitan gestionar los requerimientos detallados en la propuesta. Por ejemplo
- Gestión de análisis.
- Historial de usuarios.
- Consultas relacionadas al proyecto planteado.

**Comment by braimor** [comment]
Done
