### ISSUE TITLE
 [Formación empresarial] Plasmar el proyecto en un plan de negocios sin contar con la parte financiera 

### ISSUE THREAD

**Issue by Katherine-Damires** [Katherine-Damires/2021_Proyecto_Integrador_Equipo_4#50]
(TIR, VAN, proyecciones), mínimamente se deberán incluir:
● Nombre de la Empresa.
● Todos los ítems de la entrega anterior.
● Resumen ejecutivo.
● Análisis del mercado, oferta actual, potencial demanda y precios.
● Descripción del servicio o producto.
● Plan de marketing (Cómo se captarán los clientes)

**Comment by braimor** [comment]
Done. (haven't received any teacher's correction yet)
