### ISSUE TITLE
Login [FE]

### ISSUE THREAD

**Issue by Katherine-Damires** [Katherine-Damires/2021_Proyecto_Integrador_Equipo_4#69]
Como desarrollador
Quiero tener el layout del login
Para poder agregarle su funcionalidad.

- Al ingresar a la página debe mostrarse el home de un usuario no logueado donde en el header aparece un botón de login.

- Al pulsar el botón de login en el header debe aparecer un popup con el formulario de login igual al especificado en el figma.

Dificultad: 4.2

Link: https://www.figma.com/file/lyqY1mhYLloJZyU2VRHkk7/ideas-de-dise%C3%B1o-proyecto?node-id=72%3A161

**Comment by Agustin-1006** [comment]
Dividir la tarea en dos tanto para bakend y forntend

**Comment by Alex-Torres333** [comment]
https://www.npmjs.com/package/reactjs-popup
